function makeTestDemos()
%% Make the testDemos script

% This file is from pmtk3.googlecode.com

error('deprecated')

exclusions = {'PMTKbroken','PMTKinprogress', 'PMTKinteractive', 'PMTKreallySlow'};    % commented out in runDemos.m
demos = filenames(processExamples({}, exclusions, 0, false));
text = {'function testDemos()'
        '%% Autogenerated by makeTestDemos()'
        ''
        ''
        'errors = {};';
        ''
       };
demos = sort(demos); 

maxlen = max(cellfun(@length, text));    
for i=1:numel(demos)
   text = [text;
                 {'try'; 
                  '    close all hidden;';
                  %sprintf('    fprintf(''*******%s%s'')', demos{i}, dots(maxlen + 5 - length(demos{i})));
                  sprintf('    %sWrapper;', demos{i}); 
                  %S'    fprintf(''PASS\n'')';
                  'catch %#ok';  
                  '    fprintf(''****ERROR****'')';
                  sprintf('    errors = [errors, {''%s''}]; %#ok', demos{i}); 
                  'end'
                  ''
                  ''
                  }]; 
end

    text = [text; {'end'; ''; ''}];
    
for i=1:numel(demos)
   text = [text ; 
                {sprintf('function %sWrapper', demos{i});
                 sprintf('    %s;', demos{i}); 
                 'end';
                 '';
                 '';
                }];
end
writeText(text, fullfile(pmtk3Root(), 'toolbox', 'metatools', 'testDemos.m')); 

end
