function initPmtk3(verbose)
%% Run this script to initialize PMTK3
if nargin < 1, verbose = true; end
if verbose, disp('initializing pmtk3'); end
format compact
%%
% Change to the directory storing this function, which should be the
% root PMTK3 directory.
cd(fileparts(which(mfilename())));
%%
% Add PMTK3 to the Matlab path
addpath(pwd);
addpath(genpathPMTK(fullfile(pwd, 'toolbox')));
addpath(genpathPMTK(fullfile(pwd, 'bookDemos')));

% The following directories are initially empty
% but may be filled with stuff on demand...
addpath(genpathPMTK(fullfile(pwd, 'data')));
addpath(genpathPMTK(fullfile(pwd, 'external')), '-end');
%%
% We store user specific pmtk info in a directory they are sure to have
% write access to.
pmtkInfoDir = fullfile(tempdir(), 'pmtkInfo');
if ~exist(pmtkInfoDir, 'file')
    mkdir(pmtkInfoDir);
end
providePath(pmtkInfoDir);
%%
% Store information about which toolboxes are installed
toolbox = {'stats', 'bioinfo', 'optim', 'signal', 'images', 'symbolic',...
    'nnet', 'splines'};
for t=1:numel(toolbox)
    installed = ...
        onMatlabPath(fullfile(matlabroot, 'toolbox', toolbox{t}), true);
    fname =   sprintf('%sToolboxInstalled', toolbox{t});
    text  = { sprintf('function answer = %s()', fname)
        '% autogenerated by initPmtk3()'
        sprintf('answer = %d;', installed)
        'end'
        };
    writeText(text, fullfile(pmtkInfoDir, [fname, '.m']));
end
%%
% Check if this is Octave or Matlab
matlab = isSubstring('MATLAB', matlabroot, true);
text = { 'function answer = isOctave()'
    '%autogenerated by initPmtk3()'
    sprintf('answer = %d;', ~matlab);
    'end'
    };
writeText(text, fullfile(pmtkInfoDir, 'isOctave.m'));
%%
% Add PMTK support
% If you have a local copy of pmtkSupport, add it to your path  otherwise
% download it.
source = getConfigValue('PMTKlocalSupportPath');
if exist(source, 'dir')
    addpath(genpathPMTK(source), '-end');
end
if ~(exist('pmtkSupportRoot', 'file') == 2)
    downloadAllSupport();
end
% Add graphViz directory
if matlab && ~verLessThan('matlab', '7.6.0')
    gvizDir = getConfigValue('PMTKgvizPath'); 
    if exist(gvizDir, 'dir')
       addtosystempath(gvizDir);  
    end
end
%%
% If running windows, add the svm executables to the system path.
if ispc() && exist('pmtkSupportRoot', 'file')
    folder = pmtkSupportRoot();
    
    dirs = {'svmLightWindows'        , ...
        'liblinear-1.51\windows' , ...
        'libsvm-mat-2.9.1'       };
    
    for i=1:length(dirs)
        addtosystempath(fullfile(folder, dirs{i}))
    end
end
%%
% Add local data directory to path if it exists
source = getConfigValue('PMTKlocalDataPath');
if exist(source, 'dir')
    addpath(genpathPMTK(source));
end
%%
if verbose, disp('welcome to pmtk3'); end
end