function generatePmtkStats()
%% Generate an html page showing PMTK3 statistics such as LOC by directory.
%
% PMTKneedsMatlab
%% Settings
excludeComments             = false;
directories                 = {'toolbox', 'bookDemos'};

excludedAuthors             = {'Matt Dunham', 'Kevin Murphy'};
outputFile                  = fullfile(pmtk3Root, 'docs', 'pmtkStats.html');
recursive                   = true;
%%
colNames = {'directory', 'LOC matlab', 'LOC matlab (contrib)',...
    'LOC other', 'LOC other (contrib)', 'total LOC'};
mmask    = '*.m';
omask    = {'*.c', '*.cpp', '*.h', '*.py'};
pmtkRed  = getConfigValue('PMTKred');
%%
data = zeros(numel(directories)+1, numel(colNames)-1); % +1 for totals
countd = @(d, mask)countLinesOfCodeDir(d, excludeComments, recursive, mask);
for i=1:numel(directories)
    d = fullfile(pmtk3Root(), directories{i});
    totalMatlab   = countd(d, mmask);
    totalOther    = countd(d, omask);
    
    % assume for now that all non-matlab files are written by other people
    contribOther  = totalOther; 
    m = filelist(d, '*.m', recursive);
    authors = getTagText(m, 'PMTKauthor');
    contribFiles = m(cellfun(@(c)~isempty(setdiff(c, excludedAuthors)), authors));
    contribMatlab = sum(cellfun(@(f)countLinesOfCode(f, excludeComments), contribFiles));
    data(i, 1) = totalMatlab - contribMatlab;
    data(i, 2) = contribMatlab;
    data(i, 3) = totalOther - contribOther;
    data(i, 4) = contribOther;
    data(i, 5) = totalMatlab + totalOther;
end

if excludeComments
    excludeCommentStr = 'excludes';
else
    excludeCommentStr = 'includes';
end
data(end, :) = sum(data(1:end-1, :), 1);
header = [...
    sprintf('<font align="left" style="color:%s"><h2>PMTK Statistics</h2></font>\n', pmtkRed),...
    sprintf('<br>Revision Date: %s<br>\n', date()),...
    sprintf('<br>Auto-generated by generatePmtkStats.m<br>\n'),...
    sprintf('<br>LOC (lines of code) %s comments.<br>\n', excludeCommentStr), ...
    sprintf('Contrib means files contributed by other people (besides Dunham and Murphy).<br>\n'), ...
    sprintf('Authorship is automatically inferred based on the presence of a PMTKauthor tag.<br>\n'), ...
    sprintf('"Other" means files not written in Matlab; most such files are in C.\n'), ...
    sprintf('<br><br><br>\n')...
    ];


colNameColors = repmat({pmtkRed}, 1, numel(colNames));
htmlTable('data'            , data, ...
    'colNames'         , upper(colNames), ...
    'rowNames'         , [directories'; 'total'], ...
    'colNameColors'    , colNameColors, ...
    'header'           , header, ...
    'doshow'           , false, ...
    'dosave'           , true, ...
    'filename'         , outputFile);
end