function generateSynopses(wikiFile)
%% Generate the synopses listing files and one line desriptions
% PMTKneedsMatlab

if nargin < 1
  %wikiFile = 'C:\pmtk3wiki\synopsisPages.wiki';
  wikiFile = 'C:\kmurphy\GoogleCode\pmtk3wiki\synopsisPages.wiki';
end
dest = fullfile(pmtk3Root(), 'docs', 'synopsis'); 
%% Toolbox
d = dirs(fullfile(pmtk3Root(), 'toolbox')); 
for i=1:numel(d)
   generateSynopsisTable(fullfile(pmtk3Root(), 'toolbox', d{i}), ...
                     fullfile(dest, sprintf('%s.html', d{i})));
    
end
%% Util
generateSynopsisTable(fullfile(pmtk3Root(), 'misc', 'util'), fullfile(dest, 'util.html'));
%% Meta Tools
generateSynopsisTable(fullfile(pmtk3Root(), 'misc', 'metatools'), fullfile(dest, 'metatools.html'));
googleRoot = 'http://pmtk3.googlecode.com/svn/trunk/docs/synopsis';
wikiText = cell(numel(d), 1);
for i=1:numel(d)
    if exist(fullfile(dest, [d{i}, '.html']), 'file')
        wikiText{i} = sprintf(' * [%s/%s.html %s]',googleRoot, d{i}, d{i});
    end
end
wikiText = filterCell(wikiText, @(c)~isempty(c));
wikiText =  [{
             '#summary Synopses of all PMTK3 functions'
             'This page is auto-generated by generateSynopses'
             ''
             ''
             ''
             ''
             'This page lists the folders within PMTK. Click on the link to see the list of files in that folder, with a brief description. Click on the file to see its'
             'source code, including comments on how to use it.'
             ''
             }
            wikiText
];
            
writeText(wikiText, wikiFile); 
end