function generateSupportReport()
%% Generate the html table describing packages in pmtkSupport
% PMTKneedsMatlab 
root = pmtkSupportRoot();
dest = fullfile(root, 'docs', 'authors');
R    = pmtkTagReport(root); % get all files with tags
%%
pmtkRed = getConfigValue('PMTKred');

colNames = {'AUTHOR', 'PACKAGE NAME', 'SOURCE URL', 'DATE', 'DIRECTORY'};
fname    = fullfile(dest, 'packageAuthors.html');
packndx  = cellfun(R.filendx, R.tagmap.('PMTKtitle'))';
authors  = R.authors(packndx);
files    = R.files(packndx);
nlines   = sum(cellfun(@numel, authors));
tags     = R.tags(packndx);
tagtext  = R.tagtext(packndx);
data     = cell(nlines, length(colNames));
line     = 1;
for j=1:numel(files)
    nauth         = numel(authors{j});  % each file may have multiple authors
    directoryname = fileparts(files{j});
    directoryname = directoryname(length(root)+1:end);
    titlendx      = cellfind(tags{j}, 'PMTKtitle');
    if isempty(titlendx)
        title = '&nbsp;';
    else
        title = strtrim(tagtext{j}{titlendx});
    end
    urlndx = cellfind(tags{j}, 'PMTKurl');
    if isempty(urlndx)
        url =  '&nbsp;';
    else
        url = sprintf(' <a href="%s"> website ', strtrim(tagtext{j}{urlndx}));
    end
    datendx = cellfind(tags{j}, 'PMTKdate');
    if isempty(datendx)
        dateText = '&nbsp;';
    else
        dateText  = strtrim(tagtext{j}{datendx});
    end
    for k=1:nauth
        ndx = line+k-1;
        data{ndx, 1} = authors{j}{k};
        data{ndx, 2} = title;
        data{ndx, 3} = url;
        data{ndx, 4} = dateText;
        data{ndx, 5} = googleCodeLink(files{j}, directoryname, root);
    end
    line = line + nauth ;
end
header = [...
    sprintf('<font align="left" style="color:%s"><h2>Packages in pmtkSupport</h2></font>\n', pmtkRed),...
    sprintf('<br>Revision Date: %s<br>\n', date()),...
    sprintf('<br>Auto-generated by generateSupportReport.m<br>\n'),...
    sprintf('<br>\n')...
    ];
perm = sortidx(cellfuncell(@(c)c{end}, cellfuncell(@(c)tokenize(c, ' '), data(:, 1))));
data = data(perm, :);
htmlTable('data'           , data           , ...
    'colNames'             , colNames       , ...
    'doSave'               , true           , ...
    'filename'             , fname          , ...
    'colNameColors'        , repmat({pmtkRed}, 1, numel(colNames)), ...
    'header'               , header         , ...
    'dataAlign'            , 'left'         , ...
    'caption', '<br> <br>' , ...
    'captionLoc', 'bottom' , ...
    'doshow', false);
