function publishDemos(wikiFile)
% Publish all of the PMTK3 demos and create the wiki TOC page.
% See publishFolder, pmlCodeRefs, pmlChapterPages for settings that might
% affect this function. 
% PMTKneedsMatlab 
%%


wikiOnly = true;     % set true if you only want to regenerate the wiki and 
                     % index.html pages, and not republish. 
                
svnAutomatically = false;

if nargin == 0,  
    wikiFile = fullfile(getConfigValue('PMTKlocalWikiPath'), 'Demos.wiki'); 
end
googleRoot = 'http://pmtk3.googlecode.com/svn/trunk/docs/demoOutput';
%%
cd(fullfile(pmtk3Root(), 'demos'));
d = cellfuncell(@(c)fullfile('bookDemos', c), dirs(fullfile(pmtk3Root(), 'demos', 'bookDemos')));



    

dirEmpty = @(d)isempty(mfiles(d, 'topOnly', true));

for i = 1:numel(d)
    if ~dirEmpty(d{i})
        publishFolder(d{i}, wikiOnly);
    end
end
wikiText   = cell(numel(d), 1);
for i=1:numel(d)
    if ~dirEmpty(d{i})
        wikiText{i} = sprintf(' * [%s/%s/index.html %s]',googleRoot, d{i}, fnameOnly(d{i}));
    end
end
wikiText = filterCell(wikiText, @(c)~isempty(c));
wikiText = [{'#summary A list of every PMTK3 demo'
             'auto-generated by publishDemos'
             ''
             '== Book Demos =='
             ''
             ''
             ''
             ''
            }
            wikiText
            ];

        
%% other demos
wikiText = [wikiText; {...
    ''
    ''
    '== Other Demos == '
    '_a collection of demos not appearing in the book_'
    ''
    ''
}]; 
linkToPml = false; 
publishFolder('otherDemos', wikiOnly, linkToPml);
otherDemos = sprintf(' * [%s/%s/index.html %s]',googleRoot, 'otherDemos', 'otherDemos');
wikiText = [wikiText; otherDemos];
%%

writeText(wikiText, wikiFile);
if svnAutomatically
    system(sprintf('svn ci %s -m "auto-updated by publishDemos"', wikiFile));
    docdir = fullfile(pmtk3Root(), 'docs', 'demoOutput');
    system(sprintf('svn ci %s -m "auto-updated by publishDemos"', docdir));
end
end

