pkg:
	(cd .. && zip -r lightspeed.zip lightspeed -x \*~ -x \*.o -x \*.obj -x \*.dll -x \*.exe -x \*.lib -x \*.exp -x \*.map -x \*.mexglx -x \*.mexw32 -x \*.manifest -x \*CVS\* -x \*xrepmat.m)

clean:
	rm *~ */*~ *.dll *.exe *.obj *.o *.mexglx *.lib *.exp *.def *.map
