%% Supervised learning using generative models in pmtk3
% _This page was auto-generated by publishing_
% tutGenClassif.m
%
% (HMMs are discussed in more detail 
% <http://pmtk3.googlecode.com/svn/trunk/docs/tutorial/html/tutLVM.html
% here>.)
% (HMMs are discussed in more detail 
% <tutLVM.html here>.)
% HMMs are discussed in more detail 
% in tutLVM.html .
