function exportToGoogleCode(package, username, passwd, summary, exclusions, createEmpty)
% Export package from svn, uploading the zip to the google code repository
%
% PACKAGE      -  name of svn directory
% USERNAME     -  your google code username, e.g. mattbdunham
% PASSWD       -  your autogenerated google code password, access from
%                 https://code.google.com/hosting/settings
% SUMMARY      -  a summary of the version, to be displayed on the site.
% EXCLUIONS    -  a cell array of directories to exclude, e.g 
%                 {'docs', 'external', 'data'}
% CREATEEMPTY  -  a cell array of empty top level directories to add, e.g.
%                {'external', 'data'}
%PMTKneedsMatlab
%PMTKneedsPython
%%

% This file is from pmtk3.googlecode.com

uploadFn = which('googlecode_upload.py');
SetDefaultValue(1, 'package'     , 'pmtk3'); 
SetDefaultValue(2, 'username'    , getConfigValue('PMTKgoogleUsername'));
SetDefaultValue(3, 'passwd'      , getConfigValue('PMTKgooglePassword'))
SetDefaultValue(4, 'summary'     , date()); 
SetDefaultValue(5, 'exclusions'  , {'docs'});
SetDefaultValue(6, 'createEmpty' , {}); 
switch package
    case 'pmtk3'
        exclusions = union(exclusions, {'data', 'external', 'matlabTools'}); 
        if isempty(createEmpty)
            createEmpty = {'data', 'external', 'matlabTools'};
        end
end
%%    
rootDir = eval(sprintf('%sRoot()', package));
d = date(); 
d = d(d~='-');
zipFilePath = fullfile(tempname, [package,'-',d,'.zip']); 
mkdir(fileparts(zipFilePath)); 
fprintf('root directory is %s\n', rootDir); 
fprintf('exporting code to %s...\n', zipFilePath); 
exportsvn(rootDir, zipFilePath, exclusions, createEmpty); 
fprintf('export successful\n'); 

if 1
    fprintf('uploading file...\n');
    fprintf('executing the following command:\n'); 
    command = sprintf('python %s -s "%s" -p "%s" -u %s -w %s "%s"', ...
        uploadFn, summary, package, username, passwd, zipFilePath)
    
    fprintf('\n'); 
    [err, output] = system(command);
    if err
        error('There was a problem uploading the file:\n%s', output); 
    end
    fprintf('cleaning up...\n');
    delete(zipFilePath);
    fprintf('done\n\n')
    web(sprintf('http://code.google.com/p/%s/downloads/list', lower(package)), '-browser')
end
end
