function exportSvnToZipOnGoogleCode(username, passwd, summary)
% Cut a new release of PMTK3, uploading the zip to the google code
% repository. 
%
% USERNAME - Your google code username, e.g. mattbdunham
% PASSWD   - Your autogenerated google code password, access from
%            https://code.google.com/hosting/settings
%
% SUMMARY  - A summary of the version, to be displayed on the site. 

  error(nargchk(3, 3, nargin));
  %pmtkRoot = [fileparts(mfilename('fullpath')),filesep,'..']
  cd(pmtkRoot()); % move to pmtk3 root
  d = date(); d = d(d~='-');
  fname = ['pmtk3-',d,'.zip'];
  fpath = fullfile(tempdir, fname)
  fprintf('Root directory is %s\n',pwd)
  fprintf('Exporting code to %s...\n', fname);
  exportsvn(pwd, fpath);
  
  fprintf('Uploading file...\n');
  uploadFn = fullfile(pwd, 'util', 'googlecode_upload.py');
  fprintf('python %s -s "%s" -p "pmtk3" -u %s -w %s "%s"', uploadFn, summary, username, passwd, fpath)
  result = systemf('python %s -s "%s" -p "pmtk3" -u %s -w %s "%s"', uploadFn, summary, username, passwd, fpath)
  fprintf('Cleaning up...\n');  
  delete(fpath)  
  fprintf('Done\n\n')
  web('http://code.google.com/p/pmtk3/downloads/list','-browser')
end