function generatePmtkDataTable(dataSource)
%% Generate the PMTK data table from the meta files
% The html table is stored in the dataSource directory.
% dataSource is the location of the pmtkData local copy of the svn
% repository.


if nargin == 0
    dataSource = 'C:\pmtkData\';
end

dataSets = dirs(dataSource);
perm     = sortidx(lower(dataSets));
dataSets = dataSets(perm);
googleRoot = ' http://pmtkdata.googlecode.com/svn/trunk';
colNames = {'NAME', 'FILESIZE (KB)', 'DESCRIPTION', 'TYPE', 'NCASES', 'NDIMS', 'SOURCE'};
n = numel(dataSets);

htmlData = cell(n, numel(colNames));
for i=1:n
    meta = fullfile(dataSource, dataSets{i}, [dataSets{i}, '-meta.txt']);
    zip  = fullfile(dataSource, dataSets{i}, [dataSets{i}, '.zip']);
    link = sprintf('<a href="%s/%s/%s.zip">%s</a>', googleRoot, dataSets{i}, dataSets{i}, dataSets{i}); 
    htmlData{i, 1} = link; 
            
    [tags, lines] = tagfinder(meta);
    info = dir(zip); 
    sz = sprintf('%d', ceil(info.bytes/(1024))); 
    htmlData{i, 2} = sz; 
    
    S = createStruct(tags, lines);
    if isfield(S, 'PMTKdescription')
        htmlData{i, 3} = S.PMTKdescription;
    end
    if isfield(S, 'PMTKtype')
        htmlData{i, 4} = S.PMTKtype;
    end
    if isfield(S, 'PMTKncases')
        htmlData{i, 5} = S.PMTKncases;
    end
    if isfield(S, 'PMTKndims')
        htmlData{i, 6} = S.PMTKndims;
    end
    
    if isfield(S, 'PMTKsource')
        htmlData{i, 7} = S.PMTKsource;
    end
end
pmtkRed  = '#990000';

header = [...
    sprintf('<font align="left" style="color:%s"><h2>PMTK Data</h2></font>\n', pmtkRed),...
    sprintf('<br>Revision Date: %s<br>\n', date()),...
    sprintf('<br>Auto-generated by generatePmtkDataTable.m<br>\n'),...
    sprintf('<br>Click on the file name to download the data set.'), ...
    sprintf('<br><br><br>\n')...
    ];

colNameColors = repmat({pmtkRed}, 1, numel(colNames));
dest = fullfile(dataSource, 'dataTable.html'); 
htmlTable('data'          , htmlData       , ...
          'doshow'        , true           , ...
          'dosave'        , true           , ...
          'filename'      , dest           , ...
          'dataalign'     , 'left'         , ...
          'colnames'      , colNames       , ...
          'colNameColors' , colNameColors  , ...
          'header'        , header         );

end