function makeTestDemos()
%% Make the testDemos script

exclusions = {'PMTKbroken','PMTKinprogress', 'PMTKinteractive', 'PMTKreallySlow'};    % commented out in runDemos.m
demos = filenames(processExamples({}, exclusions, 0, false));
text = {'%% Autogenerated by makeTestDemos()'
        ''
        ''
        'errors = {};';
        ''
       };
demos = sort(demos); 

maxlen = max(cellfun(@length, text));    
for i=1:numel(demos)
   text = [text;
                 {'try'; 
                  '    close all hidden;';
                  sprintf('    fprintf(''%s%s'')', demos{i}, dots(maxlen + 5 - length(demos{i})));
                  sprintf('    %s;', demos{i}); 
                  '    fprintf(''PASS\n'')';
                  'catch %#ok';  
                  '    fprintf(''ERROR'')';
                  sprintf('    errors = [errors, {''%s''}]; %#ok', demos{i}); 
                  'end'
                  ''
                  ''
                  }]; 
end
writeText(text, fullfile(pmtk3Root(), 'misc', 'metatools', 'testDemos.m')); 

end