prepare_housing

% Scaled Norm Solvers
lambda = 100;
[LassoBlockCoordinate(X,y,lambda) ...
    LassoConstrained(X,y,lambda,'mode',2) ...
    LassoGaussSeidel(X,y,lambda) ...
    LassoGrafting(X,y,lambda) ...
    LassoIteratedRidge(X,y,lambda) ...
    LassoNonNegativeSquared(X,y,lambda) ...
    LassoPrimalDualLogBarrier(X,y,lambda) ...
    LassoProjection(X,y,lambda) ...
    LassoShooting(X,y,lambda) ...
    LassoSubGradient(X,y,lambda) ...
    LassoUnconstrainedApx(X,y,lambda) ...
    LassoUnconstrainedApx(X,y,lambda,'mode2',1)]
pause;

% Constrained Norm Solvers
t = sum(abs(ans(:,end)));
if exist('LassoLARS')
    [LassoActiveSet(X,y,t) ...
        LassoConstrained(X,y,t) ...
        LassoLARS(X,y,t) ...
        LassoSignConstraints(X,y,t)]
else
    [LassoActiveSet(X,y,t) ...
        LassoConstrained(X,y,t) ...
        LassoSignConstraints(X,y,t)]
end