function yhat = svmPredict(model, X)
% This is a simple interface to svm_light, 
% which must be on the system path. 
%
% model  - model generated by svmFit()
% yhat   - output is in {-1, 1}

% You can use the addtosystempath function to add the directory containing
% svm_classify.exe. 

    X =  mkUnitVariance(center(X));
    testOptions = '-v 3';
    tmp = tempdir();
    testFile    = fullfile(tmp, 'test.svm');
    modelFile   = model.file; 
    logFile     = fullfile(tmp, 'testLog.svm');
    resultsFile = fullfile(tmp, 'results.svm');
    svmWriteData(X, zeros(size(X, 1), 1), testFile);
    if systemf('svm_classify %s %s %s %s > %s', testOptions, testFile, modelFile, resultsFile, logFile);
       error('There was a problem executing svm_classify.exe - please make sure its on the system path');
    end
        
    yhat = sign(dlmread(resultsFile));
end