function pmtkPublish(file, varargin)
%% A modified version of the builtin publish command
% For every foo.m found in the comments, if foo.m is part of the PMTK
% suite of google code repositories, it is replaced with its full html
% link. Similarly for foo.html.
% This allows us to write 'see foo.m for details'
% and the appropriate hyper-link will be inserted.
% In addition, we put a time stamp at the end of the file.
%%

% This file is from pmtk3.googlecode.com

if nargin == 2 && isstruct(varargin{1}) && isfield(varargin{1}, 'outputDir')
    outputDir = varargin{1}.outputDir;
else
    outputDir = fullfile(fileparts(which(file)), 'html'); 
end

text = getText(file);
recycle on; % make sure deleting puts things in recycle bin


%%
latexExpand = false; % not a user setting - this gets toggled on and off automatically. 
for i=1:numel(text)
   line = text{i};
   
   if ~startswith(strtrim(line), '%')
       continue; 
   end
   
   if isSubstring('<html>', line)
       latexExpand = true; 
   elseif isSubstring('</html>', line)
       latexExpand = false; 
   end
   
   
   %% mfile exapnsion
   toks = tokenize(line, ' ');
   ndxM =  find(cellfun(@(c)endswith(strtrim(c), '.m'), toks)); 
   ndxH =  find(cellfun(@(c)endswith(strtrim(c), '.html'), toks));
   ndx = [ndxM ndxH];
   for j=1:numel(ndx)
       t = strtrim(toks{ndx(j)}); 
       link = googleCodeLink(t, t, 'publish'); 
       if ~isempty(link)
          line = strrep(line, t, link);  
       end
   end
   if latexExpand
       %% latex expansions
       toks = unSandwich(line, '$', '$');
       for j=1:numel(toks)
           t = toks{j};
           htmlLink = texifyFormula(strtrim(t), genvarname(t), outputDir);
           line = strrep(line, ['$', t, '$'], htmlLink);
       end
   end
   text{i} = line; 
end

% Add time stamp to the end
str = sprintf('%s\n%s <html>\n%s <hr>\n%s </html>\n%s\n', ...
  '%%','%','%', '%', '%%');
text{end+1} = str;
[path, fname] = fileparts(file); %#ok
str = sprintf('%s\n%s This page was auto-generated by calling _pmtkPublish(%s)_  on %s\n', ...
  '%%', '%', fname, datestr(now));
text{end+1} = str;

% Since we overwrite the user's file,
% we make a backup first.
f = which(file);
bak =  fullfile(fileparts(f), [fnameOnly(f), '.bak']);
evalc('system(sprintf(''move /Y %s %s'', f, bak))');
% Now overwrite original file
writeText(text, f);
% Now publish (modified version of) original file
if isempty(varargin)
  opts.maxHeight = 300; opts.maxWidth = 300;
  publish(file, opts);
else
  publish(file, varargin{:});
end
pause(0.1); 
fclose all; 
% Now restore original file from backup
evalc('system(sprintf(''move /Y %s %s'', bak, f))'); 
end
